#!/bin/sh

set -e

cd "$(dirname "$0")/.."

./script/bootstrap

echo "==> Building Java Project"
mvn clean install

echo "==> Building Frontend"
cd frontend
npm run build

echo "==> Installing Swagger UI"
cd ..
mkdir src/main/resources/static/swagger
cp assets/swagger-dist/* src/main/resources/static/swagger