#!/bin/sh

set -e

cd "$(dirname "$0")/.."

docker run -it -p 8080:8080 -e POSTGRES_JDBC_URL="jdbc:postgresql://docker.for.mac.host.internal:5432/hms" -e POSTGRES_USERNAME="hms" -e POSTGRES_PASSWORD="" -e MG_DOMAIN="" -e MG_API_KEY="" hms
